# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /
            logout: ~
            remember_me:
                secret: '%secret%'
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/cart/list, role: ROLE_USER }
        - { path: ^/order/list, role: ROLE_USER }
        - { path: ^/order/all, role: ROLE_ADMIN }
        - { path: ^/product/add, role: ROLE_SUPER_ADMIN }
        - { path: ^/product/edit, role: ROLE_SUPER_ADMIN }
        - { path: ^/user/list, role: ROLE_ADMIN }
        - { path: ^/user/add, role: ROLE_ADMIN }
        - { path: ^/user/edit, role: ROLE_ADMIN }
        - { path: ^/report/list, role: ROLE_ADMIN }